apps: libcamera: build force use of subproject
In libcamera v6.12.49, the dependency requirement for libyaml has
changed. Building with the default wrap-mode failed because Meson
attempted to use incompatible libyaml headers from the host/sysroot
instead of the integrated subproject. Adds --wrap-mode=forcefallback
to meson setup to ensure isolation from system-wide libyaml
installations.

build fail log:
  fatal error: yaml.h: No such file or directory